# Generated by Django 3.2.4 on 2022-06-11 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titulo')),
                ('keywords', models.CharField(max_length=255, verbose_name='Palabras clave')),
                ('publication_date', models.DateField(verbose_name='Fecha de publicacion')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookapp.file')),
                ('author', models.CharField(max_length=255, verbose_name='Autor')),
                ('summary', models.TextField(verbose_name='Descripcion')),
                ('cover', models.ImageField(upload_to='')),
            ],
            bases=('bookapp.file',),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookapp.file')),
                ('image_upload', models.ImageField(upload_to='')),
            ],
            bases=('bookapp.file',),
        ),
    ]
