# Generated by Django 3.2.4 on 2022-08-12 21:25

import bookapp.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='carrusel/', validators=[bookapp.validators.validate_image_extension], verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Carousel',
                'verbose_name_plural': 'Carousel',
                'db_table': 'carousel',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MetaKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='Palabra clave')),
            ],
            options={
                'verbose_name': 'Palabra_clave',
                'verbose_name_plural': 'Palabras_clave',
                'db_table': 'meta_keywords',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('author', models.CharField(max_length=255, verbose_name='Autor')),
                ('summary', models.TextField(null=True, verbose_name='Descripción')),
                ('video', models.FileField(upload_to='videos/%y/%m/%d', validators=[bookapp.validators.validate_video_extension], verbose_name='Video')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.category', verbose_name='Categoría')),
                ('keywords', models.ManyToManyField(to='bookapp.MetaKeyword', verbose_name='Palabras clave')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'db_table': 'videos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Autor')),
                ('link', models.URLField(verbose_name='Link')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.category', verbose_name='Categoría')),
                ('keywords', models.ManyToManyField(to='bookapp.MetaKeyword', verbose_name='Palabras clave')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'db_table': 'links',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Autor')),
                ('img', models.ImageField(upload_to='imagenes/%y/%m/%d', validators=[bookapp.validators.validate_image_extension], verbose_name='Imagen')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.category', verbose_name='Categoría')),
                ('keywords', models.ManyToManyField(to='bookapp.MetaKeyword', verbose_name='Palabras clave')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
                'db_table': 'images',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('author', models.CharField(max_length=255, verbose_name='Autor')),
                ('summary', models.TextField(verbose_name='Descripción')),
                ('file', models.FileField(upload_to='archivos/%y/%m/%d', validators=[bookapp.validators.validate_file_extension], verbose_name='Archivo')),
                ('cover', models.ImageField(null=True, upload_to='portadas/%y/%m/%d', validators=[bookapp.validators.validate_image_extension], verbose_name='Portada')),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.category', verbose_name='Categoría')),
                ('keywords', models.ManyToManyField(to='bookapp.MetaKeyword', verbose_name='Palabras clave')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'db_table': 'files',
                'ordering': ['id'],
            },
        ),
    ]
