# Generated by Django 3.2.4 on 2022-08-12 21:35

import bookapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='miniaturas/links', validators=[bookapp.validators.validate_image_extension], verbose_name='Miniatura'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='miniaturas/videos', validators=[bookapp.validators.validate_image_extension], verbose_name='Miniatura'),
        ),
    ]
