# Generated by Django 3.2.4 on 2022-06-18 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookapp.file')),
                ('author', models.CharField(max_length=255, verbose_name='Autor')),
                ('summary', models.TextField(verbose_name='Descripcion')),
                ('thumbnail', models.ImageField(upload_to='uploads/% y/% m/% d')),
            ],
            bases=('bookapp.file',),
        ),
        migrations.CreateModel(
            name='YtLink',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookapp.file')),
                ('link', models.URLField()),
            ],
            bases=('bookapp.file',),
        ),
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='book',
            name='book_upload',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
