# Generated by Django 3.2.4 on 2022-06-20 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_auto_20220618_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='file_ptr',
        ),
        migrations.RemoveField(
            model_name='video',
            name='file_ptr',
        ),
        migrations.RemoveField(
            model_name='ytlink',
            name='file_ptr',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='YtLink',
        ),
    ]
