# Generated by Django 3.2.4 on 2022-06-21 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_file_image_link_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
