# Generated by Django 3.2.4 on 2022-06-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookapp', '0005_auto_20220620_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('author', models.CharField(max_length=255, verbose_name='Autor')),
                ('summary', models.TextField(verbose_name='Descripción')),
                ('file', models.FileField(upload_to='archivos/%y/%m/%d', verbose_name='Archivo')),
                ('cover', models.ImageField(null=True, upload_to='portadas/%y/%m/%d', verbose_name='Portada')),
                ('publication_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'db_table': 'files',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('img', models.ImageField(upload_to='imagenes/%y/%m/%d', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
                'db_table': 'images',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('link', models.URLField(verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'db_table': 'links',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('author', models.CharField(max_length=255, verbose_name='Autor')),
                ('summary', models.TextField(null=True, verbose_name='Descripción')),
                ('video', models.FileField(upload_to='videos/%y/%m/%d', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'db_table': 'videos',
                'ordering': ['id'],
            },
        ),
    ]
