# Generated by Django 3.2.4 on 2022-07-13 04:26

import bookapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_file_image_link_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='carrusel/', validators=[bookapp.validators.validate_image_extension], verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Carousel',
                'verbose_name_plural': 'Carousel',
                'db_table': 'carousel',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='file',
            name='cover',
            field=models.ImageField(null=True, upload_to='portadas/%y/%m/%d', validators=[bookapp.validators.validate_image_extension], verbose_name='Portada'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='archivos/%y/%m/%d', validators=[bookapp.validators.validate_file_extension], verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='imagenes/%y/%m/%d', validators=[bookapp.validators.validate_image_extension], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos/%y/%m/%d', validators=[bookapp.validators.validate_video_extension], verbose_name='Video'),
        ),
    ]
